"""Demand service — generates trip demand based on time and environment."""

from __future__ import annotations

from dataclasses import dataclass, field

from app.core.city import City
from app.core.fleet import Fleet
from app.core.weather import Environment


@dataclass
class TripRequest:
    """A single trip generated by the demand model."""

    from_station_id: str
    to_station_id: str
    tick: int


class DemandService:
    """Generates time-aware trip demand (commuter tide simulation).

    Phase 2 goal: implement realistic NPC demand with:
    - Morning/evening commute peaks
    - Weekend vs weekday patterns
    - Weather-influenced demand scaling
    - Special-event surge generation
    """

    def __init__(self) -> None:
        self._seed = 42

    def generate_requests(
        self,
        city: City,
        fleet: Fleet,
        env: Environment,
        tick: int,
    ) -> list[TripRequest]:
        """Return trip requests for the current tick."""
        _ = city, fleet, env, tick
        return []  # stub
